### ISSUE TITLE
Query Resolver not executed if variables are missing

### ISSUE THREAD

**Issue by eigenmannmartin** [apollostack/react-apollo#412]
## Steps to Reproduce

Given a query with optional variables `text` and `text2` where `text2` is not always set.

```JS
const mutation = export default gql`
    mutation echo($text: String, $text2: String) {
        echo(text: $text, text2: $text2) 
    }
`;

```
```JS
graphql(mutation, {
    options: () => ({
        variables: {
             text: 'Some text', // <-- text2 is not set
        },
    }),
})
```

```JS
graphql(query, { // <-- Some other query
    options: () => ({
        reducer: (prev, action) => { // <- reducer gets not executed
            console.log(action);

            return prev;
        }
    }),
})
```

### Buggy Behavior

The reducer gets **not** executed. 
However if we set `variables` to either:

- `{ text: 'Some Text', text2: null }`
- `{ text: 'Some Text', text2: undefined }`

it does work as expected.

### Expected Behavior

It should treat `text2` as `undefined` or `null` and execute the reducer.

### Version
- apollo-client@0.7.1
- react-apollo@0.8.1

**Comment by eigenmannmartin** [comment]
I guess it occurs because `valueToObjectRepresentation` expects `text2` to be provided.

(home/martin/data/apollostack/apollo-client/node_modules/graphql-anywhere/src/storeUtils.ts:62:13)

**Comment by tmeasday** [comment]
@eigenmannmartin is this a bug in `apollo-client`? Does it happen if you directly call `mutate` on the store?

I don't really understand what a reducer for a `mutation` is supposed to do, btw.

**Comment by eigenmannmartin** [comment]
@tmeasday You are right! Sorry.
The reducer is set on another query - not on the mutation. (I did update it in my initial explanation)

I guess it is fundamentally an error in apollo-client because it required optional variables to be present.
But more of a problem is, that this error gets swallowed if you use react-apollo.
The request goes of and the result gets returned, but the reducer gets not executed.

I wrote a test that fails for apollo-client:
```JS
// apollo-client -> test/QueryManager.ts
 it('does execute reducers even without all variables', () => {

    // id and lovesJabba are not required
    const query = gql`
      query fetchLuke($id: String, $lovesJabba: boolean) {
        people_one(id: $id, lovesJabba: $lovesJabba) {
          name
        }
      }
    `;

    const variables = {
      id: '1',
    };

    const data = {
      people_one: {
        name: 'Luke Skywalker',
      },
    };

    function testReducer (state = false, action: any): any {
      console.log('--------------------->', state)
      return {};
    }

    const observable = createQueryManager({
      networkInterface: mockNetworkInterface(
        {
          request: { query, variables },
          result: { data: data },
        }
      )
    }).watchQuery({ query, variables, reducer: testReducer });

    return observableToPromise({ observable },
      (result) => {
        assert.deepEqual(result.data, true);
      },
    );
  });

```

This is the output:
```Bash
QueryManager does execute reducers even without all variables:
     Error: The inline argument "lovesJabba" is expected as a variable but was not provided.
      at valueToObjectRepresentation (/home/martin/data/apollostack/apollo-client/node_modules/graphql-anywhere/src/storeUtils.ts:64:13)
      at /home/martin/data/apollostack/apollo-client/node_modules/graphql-anywhere/src/storeUtils.ts:85:48
      at Array.forEach (native)
      at Object.argumentsObjectFromField (/home/martin/data/apollostack/apollo-client/node_modules/graphql-anywhere/src/storeUtils.ts:85:21)
      at executeField (/home/martin/data/apollostack/apollo-client/node_modules/graphql-anywhere/src/index.ts:186:16)
      at /home/martin/data/apollostack/apollo-client/node_modules/graphql-anywhere/src/index.ts:128:27
      at Array.forEach (native)
      at executeSelectionSet (/home/martin/data/apollostack/apollo-client/node_modules/graphql-anywhere/src/index.ts:121:27)
      at Object.graphql (/home/martin/data/apollostack/apollo-client/node_modules/graphql-anywhere/src/index.ts:101:10)
      at Object.diffQueryAgainstStore (/home/martin/data/apollostack/apollo-client/src/data/readFromStore.ts:260:33)
      at QueryManager.fetchQuery (/home/martin/data/apollostack/apollo-client/src/core/QueryManager.ts:479:13)
      at QueryManager.startQuery (/home/martin/data/apollostack/apollo-client/src/core/QueryManager.ts:651:10)
      at ObservableQuery.setUpQuery (/home/martin/data/apollostack/apollo-client/src/core/ObservableQuery.ts:445:23)
      at ObservableQuery.onSubscribe (/home/martin/data/apollostack/apollo-client/src/core/ObservableQuery.ts:385:12)
      at ObservableQuery.subscriberFunction (/home/martin/data/apollostack/apollo-client/src/core/ObservableQuery.ts:83:19)
      at ObservableQuery.Observable.subscribe (/home/martin/data/apollostack/apollo-client/src/util/Observable.ts:25:46)
      at /home/martin/data/apollostack/apollo-client/test/util/observableToPromise.ts:62:31
      at observableToPromiseAndSubscription (/home/martin/data/apollostack/apollo-client/test/util/observableToPromise.ts:37:19)
      at Object.default_1 [as default] (/home/martin/data/apollostack/apollo-client/test/util/observableToPromise.ts:103:44)
      at Context.<anonymous> (/home/martin/data/apollostack/apollo-client/test/QueryManager.ts:3513:31)
      at callFn (/home/martin/data/apollostack/apollo-client/node_modules/mocha/lib/runnable.js:345:21)
      at Test.Runnable.run (/home/martin/data/apollostack/apollo-client/node_modules/mocha/lib/runnable.js:337:7)
      at Runner.runTest (/home/martin/data/apollostack/apollo-client/node_modules/mocha/lib/runner.js:444:10)
      at /home/martin/data/apollostack/apollo-client/node_modules/mocha/lib/runner.js:550:12
      at next (/home/martin/data/apollostack/apollo-client/node_modules/mocha/lib/runner.js:361:14)
      at /home/martin/data/apollostack/apollo-client/node_modules/mocha/lib/runner.js:371:7
      at next (/home/martin/data/apollostack/apollo-client/node_modules/mocha/lib/runner.js:295:14)
      at Immediate.<anonymous> (/home/martin/data/apollostack/apollo-client/node_modules/mocha/lib/runner.js:339:5)
      at runCallback (timers.js:637:20)
      at tryOnImmediate (timers.js:610:5)
      at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by tmeasday** [comment]
I'm not sure that test is showing exactly the same thing (in this case it's showing that an exception is thrown from a query missing a variable; in the other case it was a mutation).

If I recall correctly, I think AC does expect you to set all variables (is this right @helfer?), so this isn't necessarily a bug there.

The real bug, as you pointed out, is that the exception is being swallowed somewhere between AC and RA. Perhaps you you could try putting a breakpoint on the line that exception is generated and seeing where it is caught in `react-apollo` and we can see if we can figure out a solution?

**Comment by eigenmannmartin** [comment]
@tmeasday react-apollo should treat a variable that is set to `null` or `undefined` the same way as it is not set. Optional Arguments should not be required to be set to `null` or `undefined` if you do not need them.

The Query does go through even without you setting all variables and it does return the correct data.
But the reducer gets not executed.

Even after a lot of digging I am not certain why the reducer gets not executed.

**Comment by tmeasday** [comment]
> react-apollo should treat a variable that is set to null or undefined the same way as it is not set. Optional Arguments should not be required to be set to null or undefined if you do not need them.

Are you saying this is how you'd like it to behave? Because I'm not sure that that's not how `apollo-client` works. We could open an feature request issue there if you want to change it. I don't think `react-apollo` should behave differently to `apollo-client`; that's just asking for problems.

> The Query does go through even without you setting all variables and it does return the correct data.

Hmm, this is sounding more and more like an issue with `apollo-client`

Have you tried it in the simpler case of just `client.watchQuery(..).subscribe(..)` and `client.mutate()`?

**Comment by eigenmannmartin** [comment]
closed by https://github.com/apollostack/apollo-client/pull/1174
