### ISSUE TITLE
When rendering to string on the server, shouldn't continue to load/re-render

### ISSUE THREAD

**Issue by tmeasday** [apollostack/react-apollo#72]
Not sure the above is the best description, but here's a repro:

https://github.com/tmeasday/react-apollo-ssr-repro

To repro: 

```
npm install
npm start
```

You should see:

```
> react-apollo-repro@1.0.0 start /private/tmp/react-apollo-repro
> babel-node index.js

<div data-reactroot="" data-reactid="1" data-react-checksum="1677794457"><!-- react-text: 2 -->foo <!-- /react-text --></div>
Caught an exception! { [Invariant Violation: React DOM tree root should always have a node reference.] name: 'Invariant Violation', framesToPop: 1 }
Invariant Violation: React DOM tree root should always have a node reference.
    at invariant (/private/tmp/react-apollo-repro/node_modules/fbjs/lib/invariant.js:38:15)
    at Object.getNodeFromInstance (/private/tmp/react-apollo-repro/node_modules/react/lib/ReactDOMComponentTree.js:164:67)
    at [object Object]._assign.getNativeNode (/private/tmp/react-apollo-repro/node_modules/react/lib/ReactDOMTextComponent.js:146:50)
    at Object.ReactReconciler.getNativeNode (/private/tmp/react-apollo-repro/node_modules/react/lib/ReactReconciler.js:64:29)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/private/tmp/react-apollo-repro/node_modules/react/lib/ReactMultiChild.js:319:42)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/private/tmp/react-apollo-repro/node_modules/react/lib/ReactMultiChild.js:276:12)
    at ReactDOMComponent.Mixin._updateDOMChildren (/private/tmp/react-apollo-repro/node_modules/react/lib/ReactDOMComponent.js:883:12)
    at ReactDOMComponent.Mixin.updateComponent (/private/tmp/react-apollo-repro/node_modules/react/lib/ReactDOMComponent.js:712:10)
    at ReactDOMComponent.Mixin.receiveComponent (/private/tmp/react-apollo-repro/node_modules/react/lib/ReactDOMComponent.js:668:10)
    at Object.ReactReconciler.receiveComponent (/private/tmp/react-apollo-repro/node_modules/react/lib/ReactReconciler.js:127:22)
```

I would expect it to render but not throw an error because it tries to re-render after the query completes.

**Comment by jbaxleyiii** [comment]
@tmeasday thanks for the repro! I'm hoping to get to this soon!

**Comment by jbaxleyiii** [comment]
@tmeasday could you see if https://github.com/apollostack/react-apollo/pull/75 fixes your problem?

**Comment by tmeasday** [comment]
Hey @jbaxleyiii, still seeing the problem above on my repo (and app).

I'm not sure if I'm installing the branch correctly? I did

```
git clone apollostack/react-apollo
cd react-apollo
git checkout ssr-start
npm compile
ln -s src/lib/index.js
npm link
cd [app]
npm link react-apollo
npm start
```

**Comment by tmeasday** [comment]
@jbaxleyiii I'd love to dig a bit deeper here if you can fill me in on the development process here..

**Comment by jbaxleyiii** [comment]
@tmeasday sorry for the lack of response! You should be able to do something like this:

```
git clone https://github.com/apollostack/react-apollo.git
cd react-apollo && git checkout ssr-start
npm i && npm run compile
npm link
// you have to manually change this line in the package.json
"main": "index.js", => "main": "lib/src/index.js", 

cd ../ && git clone https://github.com/tmeasday/react-apollo-ssr-repro
cd react-apollo-ssr-repro
npm i && npm link react-apollo
```

I did this locally, and I'm still getting the error 👎 So 1. the test was not fully accurate and 2. this still fails.

I think it is failing is because in SSR, `componentWillUnmount` is never called. Instead, I need to batch the updates and only run `handleQueryData` if the component has been mounted (via a switch in `componentDidMount` I'll do that and #78 first thing today!

**Comment by jbaxleyiii** [comment]
The issue with the test is our usage of jsdom so react thinks it is rendering to string on the client

**Comment by tmeasday** [comment]
I think the issue is that `componentWillMount` runs on client and server, but `componentDidMount` only runs on the client. So that's the one we want!
